[env:esp32-s3-devkitc]
platform = espressif32
platform_packages = 
    framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32/releases/download/2.0.9/esp32-2.0.9.zip
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 1500000
lib_deps =
  h2zero/NimBLE-Arduino@^2.1.0
build_flags =
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_MODE=1
  -DCORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_INFO

[platformio]
default_envs = esp32-s3-devkitc
